[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd AQI-RealTime-System/backend && python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd AQI-RealTime-System/backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
